//! The reactivity boundary: a live application state object, bridging
//! `.nowui` `state.foo.bar` dotted paths (already parsed and stored on
//! `Node::value_path`/`Node::events` — see `arena.rs`) to real Rust struct
//! fields and methods.
//!
//! `nowui-core` only defines the *interface* (`NowUiState`, `StateValue`,
//! `Event`) — no reflection, no macros, no chumsky/tiny-skia (the usual hard
//! rule). The actual field/method dispatch is generated by
//! `#[derive(NowUiState)]` in the sibling `nowui-macros` crate; the runtime
//! (`nowui-runtime`) is what calls `get`/`set`/`call` each frame.

use crate::geometry::Point;

/// A value crossing the reflection boundary in either direction: read from a
/// widget's bound state field, or written back to it (e.g. a dragged
/// `Slider`). Intentionally small — just the widget-displayable scalar types
/// `#[derive(NowUiState)]` currently supports (`String`, `bool`, and numeric
/// fields normalized to `f64`/`i64`). Not a general-purpose `Value` type.
#[derive(Debug, Clone, PartialEq)]
pub enum StateValue {
    Str(String),
    Number(f64),
    Bool(bool),
}

impl StateValue {
    pub fn as_str(&self) -> Option<&str> {
        match self {
            StateValue::Str(s) => Some(s),
            _ => None,
        }
    }

    pub fn as_f64(&self) -> Option<f64> {
        match self {
            StateValue::Number(n) => Some(*n),
            _ => None,
        }
    }

    pub fn as_bool(&self) -> Option<bool> {
        match self {
            StateValue::Bool(b) => Some(*b),
            _ => None,
        }
    }
}

/// Which kind of input triggered a dispatched `NowUiState::call` — mirrors
/// `nowui_core::EVENT_BINDING_KEYS` one-to-one.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EventKind {
    Click,
    MouseDown,
    MouseUp,
    MouseMove,
    KeyPress,
    KeyDown,
    KeyUp,
    Resize,
}

/// Passed to a dispatched handler method (`fn increment(&mut self, event:
/// &nowui_core::Event)`). Fields are populated only when meaningful for
/// `kind` (e.g. `key` is `None` for mouse events) — a placeholder-era
/// equivalent of a DOM event object, not a complete one.
#[derive(Debug, Clone)]
pub struct Event {
    pub kind: EventKind,
    pub cursor: Point,
    pub key: Option<String>,
}

/// Implemented by a live application state object — usually via
/// `#[derive(NowUiState)]` (see `nowui-macros`) rather than by hand. Every
/// method is keyed by a *dotted path with the leading `state` segment
/// already stripped* (`state.counter.count` -> `["counter", "count"]`) —
/// see `nowui-runtime`'s `state_subpath` for where that stripping happens.
pub trait NowUiState {
    /// Read the field at `path`. `None` if the path doesn't resolve to a
    /// known leaf field (unknown segment, wrong depth, or a nested state
    /// object whose own `get` returned `None`).
    fn get(&self, path: &[&str]) -> Option<StateValue>;

    /// Write `value` to the field at `path`. Returns `false` if the path
    /// doesn't exist or `value`'s variant doesn't match the field's type
    /// (e.g. writing a `Str` to a numeric field) — callers should treat that
    /// as a no-op, not a panic.
    fn set(&mut self, path: &[&str], value: StateValue) -> bool;

    /// Invoke the zero-extra-argument handler method at `path` (e.g.
    /// `["counter", "increment"]` for an `{onClick: state.counter.increment}`
    /// binding), passing `event`. Returns `false` if no such method is
    /// declared (see `#[nowui(methods(...))]` on the derive).
    fn call(&mut self, path: &[&str], event: &Event) -> bool;
}

/// The state object the plain `nowui` CLI binary uses for `.nowui` files
/// that have no accompanying Rust state struct — every `value`/event
/// binding simply resolves to nothing/no-op, identical to this engine's
/// behavior before reactivity existed. Real apps pass their own
/// `#[derive(NowUiState)]` struct to `nowui_runtime::run` instead.
#[derive(Debug, Clone, Copy, Default)]
pub struct NoState;

impl NowUiState for NoState {
    fn get(&self, _path: &[&str]) -> Option<StateValue> {
        None
    }
    fn set(&mut self, _path: &[&str], _value: StateValue) -> bool {
        false
    }
    fn call(&mut self, _path: &[&str], _event: &Event) -> bool {
        false
    }
}
